In [2]:
import pandas as pd
from unidecode import unidecode

In [8]:
# import data

states = pd.read_csv('states.csv', encoding='utf-8')
states

,UF,State,Capital,Region,Area,Population,Demographic Density,Cities count,GDP,GDP rate,Poverty,Latitude,Longitude
0,AC,Acre,Rio Branco,North,164123.738,881935,5.37,22,17201.95,0.5,0.189,-8.77,-70.55
1,AL,Alagoas,Maceió,Northeast,27843.295,3337357,119.86,102,15653.51,0.5,0.205,-9.62,-36.82
2,AM,Amazonas,Manaus,North,1559168.117,4144597,2.66,62,22936.28,0.7,0.193,-3.47,-65.10
3,AP,Amapá,Macapá,North,142470.762,845731,5.94,16,19405.11,0.6,0.128,1.41,-51.77
4,BA,Bahia,Salvador,Northeast,564722.611,14873064,26.34,417,17508.67,0.6,0.177,-13.29,-41.71
5,CE,Ceará,Fortaleza,Northeast,148894.757,9132078,61.33,184,16394.99,0.5,0.184,-5.20,-39.53
6,DF,Distrito Federal,Brasília,Center-west,5760.783,3015268,523.41,1,80502.47,2.5,0.019,-15.83,-47.86
7,ES,Espírito Santo,Vitória,Southeast,46074.444,4018650,87.22,78,28222.56,0.9,0.043,-19.19,-40.34
8,GO,Goiás,Goiânia,Center-west,340125.715,7018354,20.63,246,28308.77,0.9,0.037,-15.98,-49.86
9,MA,Maranhão,São Luís,Northeast,329642.170,7075181,21.46,217,12788.75,0.4,0.263,-5.42,-45.44
10,MG,Minas Gerais,Belo Horizonte,Southeast,586521.121,21168791,36.09,853,27282.75,0.9,0.047,-18.10,-44.38
11,MS,Mato Grosso do Sul,Campo Grande,Center-west,357145.535,2778986,7.78,79,35520.45,1.1,0.050,-20.51,-54.54
12,MT,Mato Grosso,Cuiabá,Center-west,903206.997,3484466,3.86,141,37914.00,1.2,0.059,-12.64,-55.42
13,PA,Pará,Belém,North,1245759.305,8602865,6.91,144,18549.33,0.6,0.192,-3.79,-52.48
14,PB,Paraíba,João Pessoa,Northeast,56467.239,4018127,71.16,223,15497.67,0.5,0.163,-7.28,-36.72
15,PE,Pernambuco,Recife,Northeast,98068.021,9557071,97.45,185,19164.52,0.6,0.161,-8.38,-37.86
16,PI,Piauí,Teresina,Northeast,251616.823,3273227,13.01,224,14089.78,0.4,0.216,-6.60,-42.28
17,PR,Paraná,Curitiba,South,199305.236,11433957,57.37,399,37221.00,1.2,0.030,-24.89,-51.55
18,RJ,Rio de Janeiro,Rio de Janeiro,Southeast,43750.423,17264943,394.62,92,40155.76,1.3,0.039,-22.25,-42.66
19,RN,Rio Grande do Norte,Natal,Northeast,52809.602,3506853,66.41,167,18333.19,0.6,0.130,-5.81,-36.59
20,RO,Rondônia,Porto Velho,North,237765.233,1777225,7.47,52,24092.81,0.8,0.079,-10.83,-63.34
21,RR,Roraima,Boa Vista,North,224273.831,605761,2.70,15,23158.06,0.7,0.179,1.99,-61.33
22,RS,Rio Grande do Sul,Porto Alegre,South,281707.151,11377239,40.39,497,37371.27,1.2,0.029,-30.17,-53.50
23,SC,Santa Catarina,Florianópolis,South,95730.921,7164788,74.84,295,39592.28,1.2,0.017,-27.45,-50.95
24,SE,Sergipe,Aracaju,Northeast,21926.908,2298696,104.83,75,17789.21,0.6,0.153,-10.57,-37.45
25,SP,São Paulo,São Paulo,Southeast,248219.481,45919049,184.99,645,47008.77,1.5,0.027,-22.19,-48.79
26,TO,Tocantins,Palmas,North,277720.404,1572866,5.66,139,21998.34,0.7,0.119,-9.46,-48.26

In [7]:
br_states = pd.read_csv('br-state-codes.csv', encoding='utf-8')
br_states.head()

,subdivision,region,name_prefix,name,id,idIBGE,wdId,lexLabel,creation,extinction,...,utcOffset_DST,postalCode_ranges,km2,borders,centroid_geohash,utm_zones,bounds_geohash,bounds_lat,bounds_long,notes
0,AC,N,Estado do,Acre,1,12.0,Q40780,acre,1904,NaN,...,-5.0,[69900-000 69999-999],164124.0,AM,6qmgs6fgj,18S 19S,6q52s71b3 6w8xecq4d,-11.1455614673583 -7.11182437923207,-73.9904499689999 -66.6237537659999,NaN
1,AL,NE,Estado de,Alagoas,2,27.0,Q40885,alagoas,1889,NaN,...,-3.0,[57000-000 57999-999],27848.0,BA PE SE,7nmcys499,24S 25S,7nhu3bk4p 7nrjb5e5u,-10.5011858043386 -8.81312673328604,-38.237588925 -35.1519504509999,NaN
2,AM,N,Estado do,Amazonas,3,13.0,Q40040,amazonas,1889,NaN,...,-4.0,[69000-000 69299-999]; [69400-000 69899-999],1559148.0,AC MT PA RO RR,6x602gc00,19N 20N 21N 18S 19S 20S 21S,6q780seme db2hg2zp8,-9.81804587531735 2.24663056107414,-73.8015581149999 -56.0975580379999,NaN
3,AP,N,Estado do,Amapá,4,16.0,Q40130,amapa,1943,NaN,...,-3.0,[68900-000 68999-999],142829.0,PA,db701wybj,21N 22N 22S,6zbbzqbqf dbu91p9jz,-1.23617637404071 4.43674631714571,-54.8762501799999 -49.8762166349999,NaN
4,BA,NE,Estado da,Bahia,5,29.0,Q40430,bahia,1889,NaN,...,-3.0,[40000-000 48999-999],564733.0,AL ES GO MG PE PI SE TO,7jf348gyc,23S 24S,6uwze5wry 7nmrqq9h8,-18.3485602605644 -8.53282057127726,-46.617096757 -37.341146654,NaN

In [10]:
states.to_csv("states_csv.csv", index=False, encoding="utf-8")

In [13]:
# encoding
states = states[['UF', 'State', 'Capital']]
states['State'] = states['State'].apply(unidecode)

In [15]:
states['Capital'] = states['Capital'].apply(unidecode)

In [16]:
states

    UF                State         Capital
0   AC                 Acre      Rio Branco
1   AL              Alagoas          Maceio
2   AM             Amazonas          Manaus
3   AP                Amapa          Macapa
4   BA                Bahia        Salvador
5   CE                Ceara       Fortaleza
6   DF     Distrito Federal        Brasilia
7   ES       Espirito Santo         Vitoria
8   GO                Goias         Goiania
9   MA             Maranhao        Sao Luis
10  MG         Minas Gerais  Belo Horizonte
11  MS   Mato Grosso do Sul    Campo Grande
12  MT          Mato Grosso          Cuiaba
13  PA                 Para           Belem
14  PB              Paraiba     Joao Pessoa
15  PE           Pernambuco          Recife
16  PI                Piaui        Teresina
17  PR               Parana        Curitiba
18  RJ       Rio de Janeiro  Rio de Janeiro
19  RN  Rio Grande do Norte           Natal
20  RO             Rondonia     Porto Velho
21  RR              Roraima       Boa Vista
22  RS    Rio Grande do Sul    Porto Alegre
23  SC       Santa Catarina   Florianopolis
24  SE              Sergipe         Aracaju
25  SP            Sao Paulo       Sao Paulo
26  TO            Tocantins          Palmas

In [18]:
states.to_csv("states_en.csv", index=False, encoding="utf-8")